export const GENERAL_UPDATE_REQUEST = 'GENERAL_UPDATE_REQUEST';
export const GENERAL_UPDATE_SUCCESS = 'GENERAL_UPDATE_SUCCESS';
export const GENERAL_UPDATE_FAILURE = 'GENERAL_UPDATE_FAILURE';
export const GENERAL_REQUEST = 'GENERAL_REQUEST';
export const GENERAL_FAILURE = 'GENERAL_FAILURE';
export const GENERAL_SUCCESS = 'GENERAL_SUCCESS';
